// Code generated by MockGen. DO NOT EDIT.
// Source: campaign.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCampaign is a mock of Campaign interface.
type MockCampaign struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignMockRecorder
}

// MockCampaignMockRecorder is the mock recorder for MockCampaign.
type MockCampaignMockRecorder struct {
	mock *MockCampaign
}

// NewMockCampaign creates a new mock instance.
func NewMockCampaign(ctrl *gomock.Controller) *MockCampaign {
	mock := &MockCampaign{ctrl: ctrl}
	mock.recorder = &MockCampaignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaign) EXPECT() *MockCampaignMockRecorder {
	return m.recorder
}

// StartCampaign mocks base method.
func (m *MockCampaign) StartCampaign(ctx context.Context, campaignId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCampaign", ctx, campaignId)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartCampaign indicates an expected call of StartCampaign.
func (mr *MockCampaignMockRecorder) StartCampaign(ctx, campaignId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCampaign", reflect.TypeOf((*MockCampaign)(nil).StartCampaign), ctx, campaignId)
}
