// Code generated by MockGen. DO NOT EDIT.
// Source: whatsApp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/inter-hubly/linker/internal/app/domain/dto"
	base "github.com/inter-hubly/pilot/domain/base"
)

// MockWhatsApp is a mock of WhatsApp interface.
type MockWhatsApp struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMockRecorder
}

// MockWhatsAppMockRecorder is the mock recorder for MockWhatsApp.
type MockWhatsAppMockRecorder struct {
	mock *MockWhatsApp
}

// NewMockWhatsApp creates a new mock instance.
func NewMockWhatsApp(ctrl *gomock.Controller) *MockWhatsApp {
	mock := &MockWhatsApp{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsApp) EXPECT() *MockWhatsAppMockRecorder {
	return m.recorder
}

// ChangeStatusMessage mocks base method.
func (m *MockWhatsApp) ChangeStatusMessage(ctx context.Context, message *dto.ChangeStatusDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatusMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeStatusMessage indicates an expected call of ChangeStatusMessage.
func (mr *MockWhatsAppMockRecorder) ChangeStatusMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatusMessage", reflect.TypeOf((*MockWhatsApp)(nil).ChangeStatusMessage), ctx, message)
}

// ReceiveMessage mocks base method.
func (m *MockWhatsApp) ReceiveMessage(ctx context.Context, dto *dto.WhatsAppJSONReceived) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockWhatsAppMockRecorder) ReceiveMessage(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockWhatsApp)(nil).ReceiveMessage), ctx, dto)
}

// SendMessage mocks base method.
func (m *MockWhatsApp) SendMessage(ctx context.Context, template *base.SendTextDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockWhatsAppMockRecorder) SendMessage(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockWhatsApp)(nil).SendMessage), ctx, template)
}

// StartTemplate mocks base method.
func (m *MockWhatsApp) StartTemplate(ctx context.Context, template *base.StartTemplateDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTemplate indicates an expected call of StartTemplate.
func (mr *MockWhatsAppMockRecorder) StartTemplate(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTemplate", reflect.TypeOf((*MockWhatsApp)(nil).StartTemplate), ctx, template)
}
