config:
  env: development
  port: 8081
  appId: 1121875729525113
elasticSearch:
  host: http://localhost:9200
redis:
  host: localhost:6379
  database: 0
ampq:
  host: amqp://guest:guest@rabbitmq:5672/
pgsql:
  host: postgres://postgres:postgres@postgres:5432/hubly