config:
  env: development
  port: 8081
  
  whatsAppToken: EAAP8VwxXKXkBO29cCoft0xLnHNpGyIX7ZAWiQR4ZAWXUbdBosIQ9m1vYV0Ihe1mvnEHl61yud2vIURZBTMhVS2kkFit7BJjsORTKzjH8SBKZB2yLTeZBxH0vDCeT5dM1yRXSMpRYMb2uLAoo407z4r4FEOz0Vq5n9MeVNPBj9WHxVJLpqPBlfeEzVsJLfcL5Uv15Fft3Dw7tRvvO030E21ZA7m
elasticSearch:
  host: http://localhost:9200
redis:
  host: localhost:6379
  database: 0
ampq:
  host: amqp://guest:guest@localhost:5672/
