config:
  env: development
  port: 8081
  whatsAppToken: EAAP8VwxXKXkBO5dIqlgDRnW8ngvhejrDbyfZCZCqlmGZCY0ibvgL4VXiDEcRPf9ZCEOrf0XsVBZCuOqf8XKI3Jv1cDd6jjFRRno5J6bqXWZB3aeLga8cEvO0ojbC4T0WNMyLtq8EcaKNBE5MPRVfiYPyxBvoXZB5WEPgFLGiHGrHoY3yGJfeDZACZC8kaQuDkIUixGCvGEsIGTyxlRDHxXhMp5udC
elasticSearch:
  host: http://localhost:9200
redis:
  host: localhost:6379
  database: 0
ampq:
  host: amqp://guest:guest@localhost:5672/
