config:
  env: development
  port: 8081
  whatsAppToken: EAAP8VwxXKXkBO8j4cFsVQ4s5jZCIZBKFPL2iWmTfHC7ZCaghWBQn27z6otMmFZCccyGe7pe2G9zZB5EcruHuL2ZAFID5UD6AuSXdqL5pbZCCeP40CqacgYjrZCq6OYq9Nt4X2ZC3JVlL1kTlwik8kynOSm3eDPEZCcZB37jDKG1TcYwY5ylZCQPNmQmhV04XqcpV5Mmgn1nmCAzaTr5UvaAu4UQmfTOI
elasticSearch:
  host: http://localhost:9200
redis:
  host: localhost:6379
  database: 0
ampq:
  host: amqp://guest:guest@localhost:5672/
