version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node 
      - bootstrap.memory_lock=true  
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms2g -Xmx2g 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data 
    ports:
      - "9200:9200" 
      - "9300:9300" 
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  
    ports:
      - "5601:5601" 
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elastic-network


volumes:
  esdata: 

networks:
  elastic-network: 
