// Code generated by MockGen. DO NOT EDIT.
// Source: /home/saimon/Documents/Hubly/linker/internal/service/whatsApp.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto2 "github.com/inter-hubly/linker/internal/app/domain/dto/whatsapp"
)

// MockWhatsApp is a mock of WhatsApp interface.
type MockWhatsApp struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMockRecorder
}

// MockWhatsAppMockRecorder is the mock recorder for MockWhatsApp.
type MockWhatsAppMockRecorder struct {
	mock *MockWhatsApp
}

// NewMockWhatsApp creates a new mock instance.
func NewMockWhatsApp(ctrl *gomock.Controller) *MockWhatsApp {
	mock := &MockWhatsApp{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsApp) EXPECT() *MockWhatsAppMockRecorder {
	return m.recorder
}

// ChangeStatusMessage mocks base method.
func (m *MockWhatsApp) ChangeStatusMessage(ctx context.Context, message *dto2.ChangeStatusDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatusMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeStatusMessage indicates an expected call of ChangeStatusMessage.
func (mr *MockWhatsAppMockRecorder) ChangeStatusMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatusMessage", reflect.TypeOf((*MockWhatsApp)(nil).ChangeStatusMessage), ctx, message)
}

// SentMessage mocks base method.
func (m *MockWhatsApp) SentMessage(ctx context.Context, template *dto2.SendTextDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SentMessage", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// SentMessage indicates an expected call of SentMessage.
func (mr *MockWhatsAppMockRecorder) SentMessage(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SentMessage", reflect.TypeOf((*MockWhatsApp)(nil).SentMessage), ctx, template)
}

// StartTemplate mocks base method.
func (m *MockWhatsApp) StartTemplate(ctx context.Context, template *dto2.StartTemplateDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTemplate indicates an expected call of StartTemplate.
func (mr *MockWhatsAppMockRecorder) StartTemplate(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTemplate", reflect.TypeOf((*MockWhatsApp)(nil).StartTemplate), ctx, template)
}
