// Code generated by MockGen. DO NOT EDIT.
// Source: /home/saimon/Documents/Hubly/linker/internal/repository/whatsApp.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/linker/internal/app/domain/dto"
	entity2 "github.com/inter-hubly/linker/internal/app/domain/entity"
)

// MockWhatsApp is a mock of WhatsApp interface.
type MockWhatsApp struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMockRecorder
}

// MockWhatsAppMockRecorder is the mock recorder for MockWhatsApp.
type MockWhatsAppMockRecorder struct {
	mock *MockWhatsApp
}

// NewMockWhatsApp creates a new mock instance.
func NewMockWhatsApp(ctrl *gomock.Controller) *MockWhatsApp {
	mock := &MockWhatsApp{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsApp) EXPECT() *MockWhatsAppMockRecorder {
	return m.recorder
}

// PersistMessage mocks base method.
func (m *MockWhatsApp) PersistMessage(ctx context.Context, message *entity2.Chat) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistMessage", ctx, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistMessage indicates an expected call of PersistMessage.
func (mr *MockWhatsAppMockRecorder) PersistMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistMessage", reflect.TypeOf((*MockWhatsApp)(nil).PersistMessage), ctx, message)
}

// SetStatusMessageById mocks base method.
func (m *MockWhatsApp) SetStatusMessageById(ctx context.Context, messageId string, status entity.MessageStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatusMessageById", ctx, messageId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatusMessageById indicates an expected call of SetStatusMessageById.
func (mr *MockWhatsAppMockRecorder) SetStatusMessageById(ctx, messageId, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusMessageById", reflect.TypeOf((*MockWhatsApp)(nil).SetStatusMessageById), ctx, messageId, status)
}
