// Code generated by MockGen. DO NOT EDIT.
// Source: /home/saimon/Documents/Hubly/linker/internal/gateway/whatsApp.go

// Package gateway is a generated GoMock package.
package gateway

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/inter-hubly/pilot/domain/dto"
)

// MockWhatsApp is a mock of WhatsApp interface.
type MockWhatsApp struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMockRecorder
}

// MockWhatsAppMockRecorder is the mock recorder for MockWhatsApp.
type MockWhatsAppMockRecorder struct {
	mock *MockWhatsApp
}

// NewMockWhatsApp creates a new mock instance.
func NewMockWhatsApp(ctrl *gomock.Controller) *MockWhatsApp {
	mock := &MockWhatsApp{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsApp) EXPECT() *MockWhatsAppMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockWhatsApp) GetAccessToken(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAccessToken", ctx)
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockWhatsAppMockRecorder) GetAccessToken(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockWhatsApp)(nil).GetAccessToken), ctx)
}

// ReadyMessage mocks base method.
func (m *MockWhatsApp) ReadyMessage(ctx context.Context, phoneNumberId, messageId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadyMessage", ctx, phoneNumberId, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadyMessage indicates an expected call of ReadyMessage.
func (mr *MockWhatsAppMockRecorder) ReadyMessage(ctx, phoneNumberId, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyMessage", reflect.TypeOf((*MockWhatsApp)(nil).ReadyMessage), ctx, phoneNumberId, messageId)
}

// ReceiveMessage mocks base method.
func (m *MockWhatsApp) ReceiveMessage(ctx context.Context, message *dto.WhatsAppJSONReceived) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockWhatsAppMockRecorder) ReceiveMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockWhatsApp)(nil).ReceiveMessage), ctx, message)
}

// SendMessage mocks base method.
func (m *MockWhatsApp) SendMessage(ctx context.Context, message *dto.WhatsAppJSONReceived) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockWhatsAppMockRecorder) SendMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockWhatsApp)(nil).SendMessage), ctx, message)
}
