// Code generated by MockGen. DO NOT EDIT.
// Source: /home/saimon/Documents/Hubly/linker/internal/app/gateway/keeper.go

// Package gateway is a generated GoMock package.
package gateway

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	valueobject "github.com/inter-hubly/pilot/domain/valueobject"
)

// MockKeeper is a mock of Keeper interface.
type MockKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockKeeperMockRecorder
}

// MockKeeperMockRecorder is the mock recorder for MockKeeper.
type MockKeeperMockRecorder struct {
	mock *MockKeeper
}

// NewMockKeeper creates a new mock instance.
func NewMockKeeper(ctrl *gomock.Controller) *MockKeeper {
	mock := &MockKeeper{ctrl: ctrl}
	mock.recorder = &MockKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeeper) EXPECT() *MockKeeperMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockKeeper) GetClient(ctx context.Context, clientId string) (*valueobject.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, clientId)
	ret0, _ := ret[0].(*valueobject.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockKeeperMockRecorder) GetClient(ctx, clientId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockKeeper)(nil).GetClient), ctx, clientId)
}
