// Code generated by MockGen. DO NOT EDIT.
// Source: campaign.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/pilot/domain/entity"
)

// MockCampaign is a mock of Campaign interface.
type MockCampaign struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignMockRecorder
}

// MockCampaignMockRecorder is the mock recorder for MockCampaign.
type MockCampaignMockRecorder struct {
	mock *MockCampaign
}

// NewMockCampaign creates a new mock instance.
func NewMockCampaign(ctrl *gomock.Controller) *MockCampaign {
	mock := &MockCampaign{ctrl: ctrl}
	mock.recorder = &MockCampaignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaign) EXPECT() *MockCampaignMockRecorder {
	return m.recorder
}

// GetCampaignById mocks base method.
func (m *MockCampaign) GetCampaignById(ctx context.Context, flowId string) (*entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignById", ctx, flowId)
	ret0, _ := ret[0].(*entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignById indicates an expected call of GetCampaignById.
func (mr *MockCampaignMockRecorder) GetCampaignById(ctx, flowId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignById", reflect.TypeOf((*MockCampaign)(nil).GetCampaignById), ctx, flowId)
}
