// Code generated by MockGen. DO NOT EDIT.
// Source: contact.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/pilot/domain/entity"
)

// MockContact is a mock of Contact interface.
type MockContact struct {
	ctrl     *gomock.Controller
	recorder *MockContactMockRecorder
}

// MockContactMockRecorder is the mock recorder for MockContact.
type MockContactMockRecorder struct {
	mock *MockContact
}

// NewMockContact creates a new mock instance.
func NewMockContact(ctrl *gomock.Controller) *MockContact {
	mock := &MockContact{ctrl: ctrl}
	mock.recorder = &MockContactMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContact) EXPECT() *MockContactMockRecorder {
	return m.recorder
}

// GetContactsById mocks base method.
func (m *MockContact) GetContactsById(ctx context.Context, contactsId ...string) ([]*entity.Contact, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range contactsId {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContactsById", varargs...)
	ret0, _ := ret[0].([]*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactsById indicates an expected call of GetContactsById.
func (mr *MockContactMockRecorder) GetContactsById(ctx interface{}, contactsId ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, contactsId...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactsById", reflect.TypeOf((*MockContact)(nil).GetContactsById), varargs...)
}
