// Code generated by MockGen. DO NOT EDIT.
// Source: flow.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	lentity "github.com/inter-hubly/linker/internal/app/domain/lentity"
)

// MockFlow is a mock of Flow interface.
type MockFlow struct {
	ctrl     *gomock.Controller
	recorder *MockFlowMockRecorder
}

// MockFlowMockRecorder is the mock recorder for MockFlow.
type MockFlowMockRecorder struct {
	mock *MockFlow
}

// NewMockFlow creates a new mock instance.
func NewMockFlow(ctrl *gomock.Controller) *MockFlow {
	mock := &MockFlow{ctrl: ctrl}
	mock.recorder = &MockFlowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlow) EXPECT() *MockFlowMockRecorder {
	return m.recorder
}

// GetFlowById mocks base method.
func (m *MockFlow) GetFlowById(ctx context.Context, userId string) (*lentity.Flow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowById", ctx, userId)
	ret0, _ := ret[0].(*lentity.Flow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowById indicates an expected call of GetFlowById.
func (mr *MockFlowMockRecorder) GetFlowById(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowById", reflect.TypeOf((*MockFlow)(nil).GetFlowById), ctx, userId)
}
