// Code generated by MockGen. DO NOT EDIT.
// Source: iaContext.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/inter-hubly/linker/internal/app/domain/dto"
)

// MockIaContext is a mock of IaContext interface.
type MockIaContext struct {
	ctrl     *gomock.Controller
	recorder *MockIaContextMockRecorder
}

// MockIaContextMockRecorder is the mock recorder for MockIaContext.
type MockIaContextMockRecorder struct {
	mock *MockIaContext
}

// NewMockIaContext creates a new mock instance.
func NewMockIaContext(ctrl *gomock.Controller) *MockIaContext {
	mock := &MockIaContext{ctrl: ctrl}
	mock.recorder = &MockIaContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIaContext) EXPECT() *MockIaContextMockRecorder {
	return m.recorder
}

// GetContext mocks base method.
func (m *MockIaContext) GetContext(ctx context.Context, senderId string) ([]dto.IaContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext", ctx, senderId)
	ret0, _ := ret[0].([]dto.IaContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContext indicates an expected call of GetContext.
func (mr *MockIaContextMockRecorder) GetContext(ctx, senderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockIaContext)(nil).GetContext), ctx, senderId)
}

// SaveContext mocks base method.
func (m *MockIaContext) SaveContext(ctx context.Context, senderId string, iaCompanyContext *dto.IaContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveContext", ctx, senderId, iaCompanyContext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveContext indicates an expected call of SaveContext.
func (mr *MockIaContextMockRecorder) SaveContext(ctx, senderId, iaCompanyContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveContext", reflect.TypeOf((*MockIaContext)(nil).SaveContext), ctx, senderId, iaCompanyContext)
}

// StartContext mocks base method.
func (m *MockIaContext) StartContext(ctx context.Context, senderId, iaCompanyContext string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContext", ctx, senderId, iaCompanyContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContext indicates an expected call of StartContext.
func (mr *MockIaContextMockRecorder) StartContext(ctx, senderId, iaCompanyContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContext", reflect.TypeOf((*MockIaContext)(nil).StartContext), ctx, senderId, iaCompanyContext)
}
