// Code generated by MockGen. DO NOT EDIT.
// Source: iaContext.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/pilot/domain/entity"
)

// MockFlowContext is a mock of FlowContext interface.
type MockFlowContext struct {
	ctrl     *gomock.Controller
	recorder *MockFlowContextMockRecorder
}

// MockFlowContextMockRecorder is the mock recorder for MockFlowContext.
type MockFlowContextMockRecorder struct {
	mock *MockFlowContext
}

// NewMockFlowContext creates a new mock instance.
func NewMockFlowContext(ctrl *gomock.Controller) *MockFlowContext {
	mock := &MockFlowContext{ctrl: ctrl}
	mock.recorder = &MockFlowContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowContext) EXPECT() *MockFlowContextMockRecorder {
	return m.recorder
}

// GetContext mocks base method.
func (m *MockFlowContext) GetContext(ctx context.Context, senderId string) ([]entity.Flow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext", ctx, senderId)
	ret0, _ := ret[0].([]entity.Flow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContext indicates an expected call of GetContext.
func (mr *MockFlowContextMockRecorder) GetContext(ctx, senderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockFlowContext)(nil).GetContext), ctx, senderId)
}

// SaveContext mocks base method.
func (m *MockFlowContext) SaveContext(ctx context.Context, senderId string, iaCompanyContext *entity.Flow) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveContext", ctx, senderId, iaCompanyContext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveContext indicates an expected call of SaveContext.
func (mr *MockFlowContextMockRecorder) SaveContext(ctx, senderId, iaCompanyContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveContext", reflect.TypeOf((*MockFlowContext)(nil).SaveContext), ctx, senderId, iaCompanyContext)
}

// StartContext mocks base method.
func (m *MockFlowContext) StartContext(ctx context.Context, senderId string, flowContext *entity.Flow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContext", ctx, senderId, flowContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContext indicates an expected call of StartContext.
func (mr *MockFlowContextMockRecorder) StartContext(ctx, senderId, flowContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContext", reflect.TypeOf((*MockFlowContext)(nil).StartContext), ctx, senderId, flowContext)
}
