// Code generated by MockGen. DO NOT EDIT.
// Source: variables.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVariables is a mock of Variables interface.
type MockVariables struct {
	ctrl     *gomock.Controller
	recorder *MockVariablesMockRecorder
}

// MockVariablesMockRecorder is the mock recorder for MockVariables.
type MockVariablesMockRecorder struct {
	mock *MockVariables
}

// NewMockVariables creates a new mock instance.
func NewMockVariables(ctrl *gomock.Controller) *MockVariables {
	mock := &MockVariables{ctrl: ctrl}
	mock.recorder = &MockVariablesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariables) EXPECT() *MockVariablesMockRecorder {
	return m.recorder
}

// GetVariablesByUserId mocks base method.
func (m *MockVariables) GetVariablesByUserId(ctx context.Context, userId string, variables ...string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, userId}
	for _, a := range variables {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVariablesByUserId", varargs...)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariablesByUserId indicates an expected call of GetVariablesByUserId.
func (mr *MockVariablesMockRecorder) GetVariablesByUserId(ctx, userId interface{}, variables ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, userId}, variables...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariablesByUserId", reflect.TypeOf((*MockVariables)(nil).GetVariablesByUserId), varargs...)
}
